Make sure we are dealing with AbstractProject
Otherwise it can end up with exception and user is not possible to schedule any build:

javax.servlet.ServletException: java.lang.ClassCastException: hudson.plugins.batch_task.BatchTask cannot be cast to hudson.model.AbstractProject

...

Caused by: java.lang.ClassCastException: hudson.plugins.batch_task.BatchTask cannot be cast to hudson.model.AbstractProject
       at org.jenkinsci.plugins.buildanalysis.monitor.QueueListener.shouldSchedule(QueueListener.java:39)